# Generated by Django 4.2.1 on 2023-05-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
